name: Frontend Tests Workflow

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: front-end  # Specify the working directory for this step

      - name: Run Tests
        run: npm test
        working-directory: front-end  # Specify the working directory for this step
